extends:
  import: classic
  file: pipeline.yaml
agent:
  label: jenkins-go
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/builder-go
pipelines:
  release:
    build:
      steps:
        - name: run
          image: jenkins4eval/jenkinsfile-runner
          sh: /app/bin/jenkinsfile-runner-launcher -w /app/jenkins -p /usr/share/jenkins/ref/plugins -f /workspace/source --runWorkspace /workspace/build
  pullRequest:
    build:
      steps:
        - name: run
          image: jenkins4eval/jenkinsfile-runner
          sh: /app/bin/jenkinsfile-runner-launcher -w /app/jenkins -p /usr/share/jenkins/ref/plugins -f /workspace/source --runWorkspace /workspace/build
