extends:
  import: classic
  file: go/pipeline.yaml
pipelines:
  pullRequest:
    build:
      steps:
      - sh: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/preview
        steps:
        - sh: make preview
          name: make-preview
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        - sh: jx preview --app $APP_NAME --dir ../..
          name: make-preview
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl

  release:
    build:
      steps:
      - sh: /kaniko/executor --cache=true --cache-dir=/workspace --context=/workspace/source --dockerfile=/workspace/source/Dockerfile --destination=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$VERSION --cache-repo=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/cache
        name: container-build
        image: gcr.io/kaniko-project/executor
    promote:
      steps:
      - dir: /home/jenkins/go/src/REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME/charts/REPLACE_ME_APP_NAME
        steps:
        - sh: jx step changelog --version v\$(cat ../../VERSION)
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        - comment: release the helm chart
          sh: jx step helm release
          image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        - comment: promote through all 'Auto' promotion Environments
          sh: jx-alpha-promote -b --all-auto --timeout 1h
          image: gcr.io/jenkinsxio-labs-private/jx-promote
    setVersion:
      steps:
      - sh: jx step next-version --use-git-tag-only
        name: next-version
        image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        comment: so we can retrieve the version in later steps
      - sh: jx step tag --version \$(cat VERSION) --no-apply
        image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        name: update-version
      - sh: "jx-gitops helm template"
        name: helm-template
        image: gcr.io/jenkinsxio-labs-private/jx-gitops
        comment: lets release the versioned kubernetes resources for consumption via kubectl/kpt/kustomize
      - sh: jx step tag --version \$(cat VERSION)
        image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
        name: tag-version
