agent:
  label: builder-go
  container: go
pipelines:
  pullRequest:
    build:
      steps:
        - sh: echo PR
          name: dummy-build
          container: go

  release:
    build:
      steps:
        - sh: echo Release
          name: dummy-release
          container: go
