agent:
  label: jenkins-jx-base
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/jxl
pipelines:
  pullRequest:
    build:
      steps:
        - sh: make build
          name: build
  release:
    build:
      steps:
        - sh: jx step credential -s jenkins-x-chartmuseum -k BASIC_AUTH_USER -f /builder/home/basic-auth-user.json
          name: basic-auth-username
        - sh: jx step credential -s jenkins-x-chartmuseum -k BASIC_AUTH_PASS -f /builder/home/basic-auth-pass.json
          name: basic-auth-password
        - sh: make release
          name: release
