agent:
  label: jenkins-go
  container: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/builder-go
pipelines:
  pullRequest:
    build:
      steps:
      - sh: tp
        name: build
        image: gcr.io/jstrachan-multicluster/trigger-pipeline:v3
  release:
    build:
      steps:
      - sh: tp
        name: build
        image: gcr.io/jstrachan-multicluster/trigger-pipeline:v3